### ISSUE TITLE
Rounding issue

### ISSUE THREAD

**Issue by makopov** [php/pecl-math-trader#1]
When calling the MACD function (although this seems to apply to any function in the trader library. You get rounded to 0 with any number thats less than 3 decimal places. 

For example:
```php
trader_ema([0.004, .0048, 0.0051, 0.0039], 3)
```
will output
```php
[
  2 => 0.005,
  3 => 0.004,
]
```

But this:
```php
trader_ema([0.0004, .00048, 0.00051, 0.00039], 3)
```
will round to 0
```php
[
  2 => 0.0,
  3 => 0.0,
]
```

This causes issues when dealing with pairs in crypto that have super small price values.

**Comment by cmb69** [comment]
See https://www.php.net/manual/en/trader.configuration.php#ini.trader.real-precision. For instance:
````php
<?php

ini_set("trader.real_precision", "7");
var_dump(trader_ema([0.0004, .00048, 0.00051, 0.00039], 3));
````
yields:
````
array(2) {
  [2]=>
  float(0.0004633)
  [3]=>
  float(0.0004267)
}
````

**Comment by makopov** [comment]
@cmb69 Thats awesome, thanks for sharing this!
